### PR TITLE
Marshal

### PR DESCRIPTION
**Pull request by luisdavim**
Adding convenience methods for marshalling unmarshalling and writing envs to a file.
I've also added some performance tweaks, you can review each commit separately.

### CODE REVIEW

**Comment by luisdavim** [comment]
@subosito sorry for the direct ping, I've been migrating some of the projects I help maintain from `godotenv` to `gotenv` and having these changes merged in and tagged would allow me to do it in a few  more...

**Comment by subosito** [comment]
No problem @luisdavim! I have added you as a collaborator for this project, and let's move this forward.

**Comment by subosito** [comment]
Oops, sorry @luisdavim, I forgot to merge this PR after adding you as a collaborator 😝

**Comment by luisdavim** [comment]
@subosito I'm not sure I'm added as a collaborator, GH still tags me as just a contributor and I don't have access to close issues, merge PRs or push tags...

**Comment by subosito** [comment]
@luisdavim I think you should have gotten an invitation email from GitHub, and you need to click the confirmation link.

Just let me know if you have not gotten one, and I will resend the invitation.

**Comment by luisdavim** [comment]
Ah, got it, for some reason it went to my other email address. Thanks.

**Pull request merged**
