### PR TITLE
Multiline values

### LINKED ISSUE #13: multiline ENV variable?
Do you have any plans to support multiline ENV variables?
`linePattern` regex already supports it, but `bufio.NewScanner(r)` produces variable splitted by new line separator and makes it invalid before `linePattern` applied.

### PR DESCRIPTION
**Pull request by luisdavim**
Fixes #13 and #10 

I've done some refactoring that should help improve performance a little bit, reviewing each commit individually might be easier.

### CODE REVIEW

**Comment by subosito** [comment]
Thanks, @luisdavim, this is huge! Could you please resolve the conflicts? So we can move forward.

**Comment by luisdavim** [comment]
Done, I've rebased my branch, thanks for looking into this so quickly  👍

**Comment by subosito** [comment]
Awesome!, thanks, @luisdavim 🎉

**Comment by luisdavim** [comment]
Thanks for merging this, would you mind creating a new tag?
You can also close #10 this inclues a new test confirming it's resolved.

**Comment by subosito** [comment]
Sure, @luisdavim, I have just released `v1.3.0` tag.

**Pull request merged**
